repos:
  # pip-compile-multi
  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: v2.4.5
    hooks:
      - id: pip-compile-multi-verify
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      #    -   id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
        exclude: ^tests/files/|^src/scaling/core/trainer/warnings.txt
      - id: end-of-file-fixer
        exclude: ^tests/files/|^src/scaling/core/trainer/warnings.txt
      - id: trailing-whitespace
        exclude: ^tests/files/|^src/scaling/core/trainer/warnings.txt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--select, "I,E,F", --fix]
        files: ^src|^tests
      - id: ruff-format
        exclude: ^src/scaling/core/trainer/warnings.txt
        files: ^src|^tests
